name: Python Automation CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-automation:
    runs-on: ubuntu-latest

    # Required for GUI applications
    services:
      xvfb:
        runs-on: ubuntu-latest
        container: node:16
        options: --net host
        ports:
          - 5900:5900

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb
          pip install --upgrade pip
          pip install selenium webdriver-manager python-dotenv pyvirtualdisplay

      - name: Install Chrome
        run: |
          sudo apt-get install -y google-chrome-stable
          google-chrome --version

      - name: Run Block Site Visit Script
        env:
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          TENANT_URL: ${{ secrets.TENANT_URL }}
          ASSIGNED_USERNAME: ${{ secrets.ASSIGNED_USERNAME }}
          ASSIGNED_PASSWORD: ${{ secrets.ASSIGNED_PASSWORD }}
          BROWSER: "chrome"
          POLICY_TYPE: ${{ secrets.POLICY_TYPE }}
          EXTENSION_PATH: ${{ secrets.EXTENSION_PATH }}
        run: |
          # Clean up any existing Chrome processes
          pkill -o -f "chrome" || true
          
          # Start virtual display for GUI
          Xvfb :99 -screen 0 1920x1080x24 &
          export DISPLAY=:99
          
          python Block_site_visit_AI_manual.py
