name: Python Automation CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-automation:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:4.21.0
        ports:
          - 4444:4444
        volumes:
          - ./extensions:/tmp/extensions  # Mount extensions directory

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install selenium webdriver-manager python-dotenv

      - name: Run Block Block Site Visit Script
        env:
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          TENANT_URL: ${{ secrets.TENANT_URL }}
          ASSIGNED_USERNAME: ${{ secrets.ASSIGNED_USERNAME }}
          ASSIGNED_PASSWORD: ${{ secrets.ASSIGNED_PASSWORD }}
          BROWSER: "chrome"
          POLICY_TYPE: ${{ secrets.POLICY_TYPE }}
          EXTENSION_PATH: "/tmp/extensions"  # Path inside container
        run: |
          python Block_site_visit_AI_manual.py
          
      - name: Upload Debug Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: selenium-debug
          path: |
            block_check_failure_*.png
            page_source_*.html
            retention-days: 3
