name: Python Automation CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libxss1 libgtk-3-0 libgdk-pixbuf2.0-0 \
          libnss3-dev libatk1.0-0 libatk-bridge2.0-0 libcups2 libxcomposite1 \
          libxdamage1 libxfixes3 libxrandr2 libgbm1 libpango-1.0-0 libcairo2 \
          libasound2 fonts-liberation libappindicator3-1 libnspr4 libdrm2 \
          libxshmfence1 libx11-xcb1

      - name: Install Chrome
        run: |
          sudo apt-get install -y google-chrome-stable
          sudo rm -f /etc/apt/sources.list.d/google-chrome.list
          echo "Chrome version: $(google-chrome --version)"

      - name: Install Python Packages
        run: |
          pip install --upgrade pip
          pip install selenium webdriver-manager python-dotenv pyvirtualdisplay

      - name: Setup Virtual Display
        run: |
          Xvfb :99 -screen 0 1920x1080x24 -ac +extension GLX +render -noreset > /dev/null 2>&1 &
          echo "DISPLAY=:99" >> $GITHUB_ENV
          sleep 5

      - name: Run Tests
        env:
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          TENANT_URL: ${{ secrets.TENANT_URL }}
          ASSIGNED_USERNAME: ${{ secrets.ASSIGNED_USERNAME }}
          ASSIGNED_PASSWORD: ${{ secrets.ASSIGNED_PASSWORD }}
          BROWSER: "chrome"
          POLICY_TYPE: ${{ secrets.POLICY_TYPE }}
          EXTENSION_PATH: ${{ secrets.EXTENSION_PATH }}
        run: |
          # Clean up any existing processes
          pkill -f "chrome|chromedriver|Xvfb" || true
          
          # Run test script
          python Block_site_visit_AI_manual.py

      - name: Cleanup
        if: always()
        run: |
          pkill -f "chrome|chromedriver|Xvfb" || true
          rm -rf /tmp/.com.google.Chrome* || true
          rm -rf /tmp/.org.chromium.Chromium* || true
