name: Python Automation CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install selenium webdriver-manager python-dotenv

      - name: Install Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: 'latest'

      - name: Verify Chrome Installation
        run: |
          google-chrome --version
          which google-chrome

      - name: Run Block Site Visit Script
        env:
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          TENANT_URL: ${{ secrets.TENANT_URL }}
          ASSIGNED_USERNAME: ${{ secrets.ASSIGNED_USERNAME }}
          ASSIGNED_PASSWORD: ${{ secrets.ASSIGNED_PASSWORD }}
          BROWSER: ${{ secrets.BROWSER }}
          POLICY_TYPE: ${{ secrets.POLICY_TYPE }}
          EXTENSION_PATH: ${{ secrets.EXTENSION_PATH }}
        run: |
          # Add a small delay to ensure Chrome is fully installed
          sleep 5
          python Block_site_visit_AI_manual.py

      # - name: Upload Artifacts (if needed)
      #   if: always()
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: automation-screenshots
      #     path: screenshots/
